import torch.nn as nn
import torch.nn.functional as F


class BaseActor(nn.Module):
    """
    Virtual actor network whose weights are generated by HyperNetwork.
    """

    def __init__(self, input_dim, hidden_dim1, hidden_dim2, action_dim):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim1)
        self.fc2 = nn.Linear(hidden_dim1, hidden_dim2)
        self.fc3 = nn.Linear(hidden_dim2, action_dim)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        return self.fc3(x)
